### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by BinaryBrain** [BinaryBrain/Elodie-Dream#3]
# TODO List
## Important et pas long
- [x] Fichier avec toutes les constantes utilisées (paths, filename, gravité, vitesse, etc.)
## Haute priorité
- [x] Parser les JSON, traiter, stocker les données pour les Sprites et les Tiles @Flagoul
- [x] Système de collision (classe/argument Collidable, tableau de collisionable) @Gerardufoin 
- [x] Mettre des Entities sur la Map @BinaryBrain
## Basse priorité
- [x] Afficher le ciel
- [x] Camera suivant Elodie et rapprochée
- [x] Système de Menu (qui appelle Game.save, Game.poney)
- [ ] Système d'objet
- [x] Système de sort/d'attaque
- [ ] Écran d'inventaire/sorts
- [ ] Dev Mode (Séléction d’un level, Scroll on/off)
  se balader dans la map
